// Exercise library - FitHome
// 52 home-friendly exercises, Thai + English.

class Exercise {
  final String id;
  final String nameEn;
  final String nameTh;
  final String muscle; // chest, legs, core, back, shoulders, arms, cardio
  final int difficulty; // 1 easy, 2 medium, 3 hard
  final String equipEn;
  final String equipTh;
  final List<String> stepsEn;
  final List<String> stepsTh;
  final String cautionEn;
  final String cautionTh;

  const Exercise({
    required this.id,
    required this.nameEn,
    required this.nameTh,
    required this.muscle,
    required this.difficulty,
    this.equipEn = 'None',
    this.equipTh = 'ไม่ใช้อุปกรณ์',
    required this.stepsEn,
    required this.stepsTh,
    required this.cautionEn,
    required this.cautionTh,
  });
}

const List<Exercise> exercises = [
  // ================= CHEST =================
  Exercise(
    id: 'pushup',
    nameEn: 'Push-up',
    nameTh: 'วิดพื้น',
    muscle: 'chest',
    difficulty: 2,
    stepsEn: [
      'Start in a high plank, hands slightly wider than shoulders.',
      'Lower your chest until it nearly touches the floor, elbows about 45 degrees.',
      'Push back up until arms are straight. Keep body in one line.',
    ],
    stepsTh: [
      'เริ่มท่าแพลงก์แขนตรง มือกว้างกว่าไหล่เล็กน้อย',
      'ลดตัวลงจนอกเกือบแตะพื้น ศอกกางประมาณ 45 องศา',
      'ดันตัวขึ้นจนแขนตรง เกร็งลำตัวให้เป็นเส้นตรงตลอด',
    ],
    cautionEn: 'Do not let hips sag or pike up.',
    cautionTh: 'อย่าปล่อยสะโพกตกหรือยกก้นสูงเกินไป',
  ),
  Exercise(
    id: 'knee_pushup',
    nameEn: 'Knee Push-up',
    nameTh: 'วิดพื้นเข่า',
    muscle: 'chest',
    difficulty: 1,
    stepsEn: [
      'Kneel and place hands under shoulders, body straight from knees to head.',
      'Lower chest toward the floor with control.',
      'Push back up to the start.',
    ],
    stepsTh: [
      'คุกเข่า วางมือใต้หัวไหล่ ลำตัวตรงจากเข่าถึงศีรษะ',
      'ลดอกลงหาพื้นอย่างควบคุม',
      'ดันตัวกลับขึ้นท่าเริ่มต้น',
    ],
    cautionEn: 'Use a mat under the knees.',
    cautionTh: 'ควรมีเสื่อรองเข่า',
  ),
  Exercise(
    id: 'incline_pushup',
    nameEn: 'Incline Push-up',
    nameTh: 'วิดพื้นมือสูง',
    muscle: 'chest',
    difficulty: 1,
    equipEn: 'Sturdy table or chair',
    equipTh: 'โต๊ะหรือเก้าอี้ที่มั่นคง',
    stepsEn: [
      'Place hands on a sturdy table or chair edge, body straight.',
      'Lower chest to the edge, elbows at 45 degrees.',
      'Push back up. Higher surface = easier.',
    ],
    stepsTh: [
      'วางมือบนขอบโต๊ะหรือเก้าอี้ที่มั่นคง ลำตัวตรง',
      'ลดอกลงหาขอบ ศอกกาง 45 องศา',
      'ดันตัวขึ้น ยิ่งพื้นผิวสูงยิ่งง่าย',
    ],
    cautionEn: 'Make sure the surface cannot slide.',
    cautionTh: 'ตรวจว่าโต๊ะ/เก้าอี้ไม่เลื่อน',
  ),
  Exercise(
    id: 'decline_pushup',
    nameEn: 'Decline Push-up',
    nameTh: 'วิดพื้นเท้าสูง',
    muscle: 'chest',
    difficulty: 3,
    equipEn: 'Chair or bench',
    equipTh: 'เก้าอี้หรือม้านั่ง',
    stepsEn: [
      'Put feet on a chair, hands on the floor under shoulders.',
      'Lower your chest to the floor with control.',
      'Push back up, keeping core tight.',
    ],
    stepsTh: [
      'วางเท้าบนเก้าอี้ มืออยู่บนพื้นใต้หัวไหล่',
      'ลดอกลงหาพื้นอย่างควบคุม',
      'ดันตัวขึ้น เกร็งหน้าท้องตลอด',
    ],
    cautionEn: 'Skip if you have wrist or shoulder pain.',
    cautionTh: 'เลี่ยงถ้ามีอาการเจ็บข้อมือหรือหัวไหล่',
  ),
  Exercise(
    id: 'wide_pushup',
    nameEn: 'Wide Push-up',
    nameTh: 'วิดพื้นมือกว้าง',
    muscle: 'chest',
    difficulty: 2,
    stepsEn: [
      'Set hands wider than a normal push-up, about 1.5x shoulder width.',
      'Lower until chest is near the floor.',
      'Press back up, squeezing the chest.',
    ],
    stepsTh: [
      'วางมือกว้างกว่าวิดพื้นปกติ ประมาณ 1.5 เท่าของไหล่',
      'ลดตัวลงจนอกใกล้พื้น',
      'ดันขึ้นพร้อมบีบกล้ามอก',
    ],
    cautionEn: 'Do not flare elbows fully out to 90 degrees.',
    cautionTh: 'อย่ากางศอกจนถึง 90 องศา เสี่ยงบาดเจ็บไหล่',
  ),
  Exercise(
    id: 'diamond_pushup',
    nameEn: 'Diamond Push-up',
    nameTh: 'วิดพื้นเพชร',
    muscle: 'arms',
    difficulty: 3,
    stepsEn: [
      'Place hands together under chest, thumbs and index fingers forming a diamond.',
      'Lower chest toward your hands, elbows close to the body.',
      'Push up. Works triceps and inner chest.',
    ],
    stepsTh: [
      'วางมือชิดกันใต้อก นิ้วโป้งและนิ้วชี้ทำรูปเพชร',
      'ลดอกลงหามือ ศอกแนบลำตัว',
      'ดันขึ้น เน้นไทรเซปและอกด้านใน',
    ],
    cautionEn: 'Drop to knees if form breaks.',
    cautionTh: 'ถ้าฟอร์มเสียให้ลงเข่าช่วย',
  ),
  Exercise(
    id: 'archer_pushup',
    nameEn: 'Archer Push-up',
    nameTh: 'วิดพื้นนักธนู',
    muscle: 'chest',
    difficulty: 3,
    stepsEn: [
      'Take a very wide hand position.',
      'Lower toward one hand while the other arm stays straight.',
      'Push up and repeat on the other side.',
    ],
    stepsTh: [
      'วางมือกว้างมากกว่าปกติ',
      'ลดตัวลงไปทางมือข้างหนึ่ง อีกแขนเหยียดตรง',
      'ดันขึ้นแล้วสลับข้าง',
    ],
    cautionEn: 'Advanced move - master wide push-ups first.',
    cautionTh: 'ท่ายาก ควรเล่นวิดพื้นมือกว้างให้คล่องก่อน',
  ),
  Exercise(
    id: 'chest_squeeze_pushup',
    nameEn: 'Slow Tempo Push-up',
    nameTh: 'วิดพื้นช้า (เทมโป้)',
    muscle: 'chest',
    difficulty: 2,
    stepsEn: [
      'Perform a push-up lowering for a slow 3-second count.',
      'Pause 1 second at the bottom.',
      'Push up in 1 second. Constant tension.',
    ],
    stepsTh: [
      'วิดพื้นโดยลดตัวลงช้าๆ นับ 3 วินาที',
      'ค้างจุดต่ำสุด 1 วินาที',
      'ดันขึ้นใน 1 วินาที เกร็งกล้ามเนื้อตลอด',
    ],
    cautionEn: 'Keep breathing - do not hold your breath.',
    cautionTh: 'หายใจสม่ำเสมอ อย่ากลั้นหายใจ',
  ),

  // ================= LEGS =================
  Exercise(
    id: 'squat',
    nameEn: 'Bodyweight Squat',
    nameTh: 'สควอท',
    muscle: 'legs',
    difficulty: 1,
    stepsEn: [
      'Stand with feet shoulder-width, toes slightly out.',
      'Sit hips back and down until thighs are parallel to the floor.',
      'Drive through heels to stand back up.',
    ],
    stepsTh: [
      'ยืนเท้ากว้างเท่าไหล่ ปลายเท้าชี้ออกเล็กน้อย',
      'ดันสะโพกไปหลังแล้วย่อลงจนต้นขาขนานพื้น',
      'ออกแรงส้นเท้าดันตัวขึ้นยืน',
    ],
    cautionEn: 'Keep knees tracking over toes, chest up.',
    cautionTh: 'ให้เข่าชี้ทางเดียวกับปลายเท้า อกตั้งตรง',
  ),
  Exercise(
    id: 'jump_squat',
    nameEn: 'Jump Squat',
    nameTh: 'สควอทกระโดด',
    muscle: 'legs',
    difficulty: 2,
    stepsEn: [
      'Squat down until thighs are parallel.',
      'Explode up into a jump.',
      'Land softly on bent knees and go straight into the next rep.',
    ],
    stepsTh: [
      'ย่อสควอทจนต้นขาขนานพื้น',
      'กระโดดขึ้นสุดแรง',
      'ลงพื้นเบาๆ ด้วยเข่างอ แล้วต่อครั้งถัดไป',
    ],
    cautionEn: 'Land softly - avoid on hard knee pain days.',
    cautionTh: 'ลงพื้นให้นุ่ม เลี่ยงถ้าเจ็บเข่า',
  ),
  Exercise(
    id: 'lunge',
    nameEn: 'Forward Lunge',
    nameTh: 'ลันจ์',
    muscle: 'legs',
    difficulty: 1,
    stepsEn: [
      'Step one foot forward into a long stride.',
      'Lower until both knees are about 90 degrees.',
      'Push off the front foot to return. Alternate legs.',
    ],
    stepsTh: [
      'ก้าวเท้าหนึ่งไปข้างหน้ายาวๆ',
      'ย่อตัวลงจนเข่าทั้งสองงอประมาณ 90 องศา',
      'ดันเท้าหน้ากลับมายืน สลับขา',
    ],
    cautionEn: 'Front knee should not pass far beyond toes.',
    cautionTh: 'เข่าหน้าไม่ควรเลยปลายเท้ามากเกินไป',
  ),
  Exercise(
    id: 'reverse_lunge',
    nameEn: 'Reverse Lunge',
    nameTh: 'ลันจ์ถอยหลัง',
    muscle: 'legs',
    difficulty: 1,
    stepsEn: [
      'Step one foot backward.',
      'Lower the back knee toward the floor.',
      'Push back up to standing. Alternate legs.',
    ],
    stepsTh: [
      'ก้าวเท้าหนึ่งถอยไปด้านหลัง',
      'ย่อเข่าหลังลงหาพื้น',
      'ดันตัวกลับขึ้นยืน สลับขา',
    ],
    cautionEn: 'Easier on the knees than forward lunges.',
    cautionTh: 'ท่านี้เป็นมิตรกับเข่ามากกว่าลันจ์ไปหน้า',
  ),
  Exercise(
    id: 'bulgarian_split_squat',
    nameEn: 'Bulgarian Split Squat',
    nameTh: 'สปลิทสควอทขาหลังวางเก้าอี้',
    muscle: 'legs',
    difficulty: 3,
    equipEn: 'Chair',
    equipTh: 'เก้าอี้',
    stepsEn: [
      'Stand in front of a chair, rest one foot on it behind you.',
      'Lower until the front thigh is parallel to the floor.',
      'Drive up through the front heel. Finish reps then switch legs.',
    ],
    stepsTh: [
      'ยืนหน้าเก้าอี้ วางหลังเท้าข้างหนึ่งบนเก้าอี้',
      'ย่อลงจนต้นขาหน้าขนานพื้น',
      'ดันส้นเท้าหน้าขึ้น ทำครบเซ็ตแล้วสลับขา',
    ],
    cautionEn: 'Keep torso upright, do not bounce.',
    cautionTh: 'ลำตัวตั้งตรง อย่ากระแทกตัวลง',
  ),
  Exercise(
    id: 'glute_bridge',
    nameEn: 'Glute Bridge',
    nameTh: 'สะพานสะโพก',
    muscle: 'legs',
    difficulty: 1,
    stepsEn: [
      'Lie on your back, knees bent, feet flat near hips.',
      'Squeeze glutes and lift hips until body is straight from knees to shoulders.',
      'Pause, then lower slowly.',
    ],
    stepsTh: [
      'นอนหงาย ชันเข่า วางเท้าราบใกล้สะโพก',
      'บีบก้นแล้วยกสะโพกขึ้นจนลำตัวตรงจากเข่าถึงไหล่',
      'ค้างสักครู่แล้วลดลงช้าๆ',
    ],
    cautionEn: 'Do not overarch the lower back at the top.',
    cautionTh: 'อย่าแอ่นหลังส่วนล่างเกินไปตอนยกสุด',
  ),
  Exercise(
    id: 'single_leg_bridge',
    nameEn: 'Single-leg Glute Bridge',
    nameTh: 'สะพานสะโพกขาเดียว',
    muscle: 'legs',
    difficulty: 2,
    stepsEn: [
      'Set up like a glute bridge, extend one leg straight.',
      'Lift hips using the planted leg only.',
      'Lower slowly. Finish reps then switch legs.',
    ],
    stepsTh: [
      'ท่าเดียวกับสะพานสะโพก แต่เหยียดขาหนึ่งตรง',
      'ยกสะโพกขึ้นด้วยขาที่วางพื้นข้างเดียว',
      'ลดลงช้าๆ ครบเซ็ตแล้วสลับขา',
    ],
    cautionEn: 'Keep hips level - do not twist.',
    cautionTh: 'รักษาสะโพกให้ขนานพื้น อย่าบิดตัว',
  ),
  Exercise(
    id: 'calf_raise',
    nameEn: 'Calf Raise',
    nameTh: 'เขย่งน่อง',
    muscle: 'legs',
    difficulty: 1,
    stepsEn: [
      'Stand tall, hold a wall for balance if needed.',
      'Rise up onto the balls of your feet as high as possible.',
      'Lower slowly below start level if on a step.',
    ],
    stepsTh: [
      'ยืนตรง จับกำแพงช่วยทรงตัวได้',
      'เขย่งปลายเท้าขึ้นให้สูงที่สุด',
      'ลดส้นลงช้าๆ',
    ],
    cautionEn: 'Move slowly for a full stretch.',
    cautionTh: 'ทำช้าๆ ให้น่องยืดเต็มช่วง',
  ),
  Exercise(
    id: 'wall_sit',
    nameEn: 'Wall Sit',
    nameTh: 'นั่งพิงกำแพง',
    muscle: 'legs',
    difficulty: 2,
    equipEn: 'Wall',
    equipTh: 'กำแพง',
    stepsEn: [
      'Lean your back flat against a wall.',
      'Slide down until knees are at 90 degrees, feet under knees.',
      'Hold the position for the target time.',
    ],
    stepsTh: [
      'พิงหลังแนบกำแพง',
      'ไถลตัวลงจนเข่างอ 90 องศา เท้าอยู่ใต้เข่า',
      'ค้างท่าตามเวลาที่กำหนด',
    ],
    cautionEn: 'Keep breathing steadily while holding.',
    cautionTh: 'หายใจสม่ำเสมอระหว่างค้างท่า',
  ),
  Exercise(
    id: 'step_up',
    nameEn: 'Step-up',
    nameTh: 'ก้าวขึ้นเก้าอี้',
    muscle: 'legs',
    difficulty: 2,
    equipEn: 'Sturdy chair or step',
    equipTh: 'เก้าอี้มั่นคงหรือขั้นบันได',
    stepsEn: [
      'Place one foot fully on a sturdy chair or step.',
      'Drive through that heel to step up until the leg is straight.',
      'Lower slowly with control. Alternate legs.',
    ],
    stepsTh: [
      'วางเท้าหนึ่งเต็มฝ่าเท้าบนเก้าอี้หรือขั้นบันไดที่มั่นคง',
      'ออกแรงส้นเท้าดันตัวขึ้นจนขาตรง',
      'ลงช้าๆ อย่างควบคุม สลับขา',
    ],
    cautionEn: 'Check the chair is stable before starting.',
    cautionTh: 'ตรวจความมั่นคงของเก้าอี้ก่อนเริ่ม',
  ),
  Exercise(
    id: 'side_lunge',
    nameEn: 'Side Lunge',
    nameTh: 'ลันจ์ด้านข้าง',
    muscle: 'legs',
    difficulty: 2,
    stepsEn: [
      'Step wide to one side.',
      'Bend that knee and sit back, other leg straight.',
      'Push back to center. Alternate sides.',
    ],
    stepsTh: [
      'ก้าวเท้ากว้างออกด้านข้าง',
      'งอเข่าข้างนั้นแล้วย่อ อีกขาเหยียดตรง',
      'ดันตัวกลับกลางแล้วสลับข้าง',
    ],
    cautionEn: 'Keep the bent knee over the foot.',
    cautionTh: 'เข่าที่งอต้องอยู่แนวเดียวกับเท้า',
  ),
  Exercise(
    id: 'pistol_squat',
    nameEn: 'Pistol Squat (assisted)',
    nameTh: 'สควอทขาเดียว (มีตัวช่วย)',
    muscle: 'legs',
    difficulty: 3,
    equipEn: 'Door frame or pole to hold',
    equipTh: 'วงกบประตูหรือเสาสำหรับจับ',
    stepsEn: [
      'Hold a door frame, lift one leg straight in front.',
      'Squat down on the standing leg as low as controlled.',
      'Pull lightly with hands to help stand up. Switch legs.',
    ],
    stepsTh: [
      'จับวงกบประตู ยกขาหนึ่งเหยียดไปหน้า',
      'ย่อลงด้วยขาที่ยืนให้ลึกเท่าที่คุมได้',
      'ใช้มือช่วยดึงเบาๆ ตอนยืนขึ้น สลับขา',
    ],
    cautionEn: 'Very advanced - progress slowly.',
    cautionTh: 'ท่ายากมาก ค่อยๆ ฝึกทีละขั้น',
  ),

  // ================= CORE =================
  Exercise(
    id: 'plank',
    nameEn: 'Plank',
    nameTh: 'แพลงก์',
    muscle: 'core',
    difficulty: 1,
    stepsEn: [
      'Rest on forearms and toes, elbows under shoulders.',
      'Squeeze abs and glutes, body in one straight line.',
      'Hold for the target time.',
    ],
    stepsTh: [
      'ยันตัวด้วยปลายแขนและปลายเท้า ศอกอยู่ใต้ไหล่',
      'เกร็งหน้าท้องและก้น ลำตัวเป็นเส้นตรง',
      'ค้างท่าตามเวลาที่กำหนด',
    ],
    cautionEn: 'Do not let hips drop or rise.',
    cautionTh: 'อย่าปล่อยสะโพกตกหรือยกสูง',
  ),
  Exercise(
    id: 'side_plank',
    nameEn: 'Side Plank',
    nameTh: 'แพลงก์ด้านข้าง',
    muscle: 'core',
    difficulty: 2,
    stepsEn: [
      'Lie on one side, prop up on your forearm, elbow under shoulder.',
      'Lift hips so the body forms a straight line.',
      'Hold, then switch sides.',
    ],
    stepsTh: [
      'นอนตะแคง ยันปลายแขน ศอกอยู่ใต้ไหล่',
      'ยกสะโพกขึ้นให้ลำตัวเป็นเส้นตรง',
      'ค้างท่าแล้วสลับข้าง',
    ],
    cautionEn: 'Drop the bottom knee to make it easier.',
    cautionTh: 'วางเข่าล่างลงพื้นได้ถ้ายากไป',
  ),
  Exercise(
    id: 'crunch',
    nameEn: 'Crunch',
    nameTh: 'ครันช์',
    muscle: 'core',
    difficulty: 1,
    stepsEn: [
      'Lie on your back, knees bent, hands lightly behind ears.',
      'Curl shoulders off the floor using your abs.',
      'Lower slowly. Do not pull the neck.',
    ],
    stepsTh: [
      'นอนหงาย ชันเข่า มือแตะข้างหูเบาๆ',
      'ใช้หน้าท้องยกไหล่ขึ้นจากพื้น',
      'ลดลงช้าๆ ห้ามดึงคอ',
    ],
    cautionEn: 'Movement is small - shoulders only, not full sit-up.',
    cautionTh: 'ยกแค่หัวไหล่พอ ไม่ต้องลุกทั้งตัว',
  ),
  Exercise(
    id: 'bicycle_crunch',
    nameEn: 'Bicycle Crunch',
    nameTh: 'ครันช์จักรยาน',
    muscle: 'core',
    difficulty: 2,
    stepsEn: [
      'Lie back, hands behind ears, legs lifted.',
      'Bring one elbow toward the opposite knee while extending the other leg.',
      'Alternate sides in a pedaling motion.',
    ],
    stepsTh: [
      'นอนหงาย มือแตะข้างหู ยกขาขึ้น',
      'บิดศอกหาเข่าฝั่งตรงข้าม พร้อมเหยียดขาอีกข้าง',
      'สลับข้างเหมือนปั่นจักรยาน',
    ],
    cautionEn: 'Rotate from the torso, not the neck.',
    cautionTh: 'บิดจากลำตัว ไม่ใช่จากคอ',
  ),
  Exercise(
    id: 'leg_raise',
    nameEn: 'Lying Leg Raise',
    nameTh: 'นอนยกขา',
    muscle: 'core',
    difficulty: 2,
    stepsEn: [
      'Lie flat, hands under hips for support.',
      'Raise straight legs to vertical.',
      'Lower slowly without letting the lower back arch.',
    ],
    stepsTh: [
      'นอนราบ สอดมือใต้สะโพกช่วยพยุง',
      'ยกขาตรงขึ้นตั้งฉากกับพื้น',
      'ลดขาลงช้าๆ อย่าให้หลังแอ่น',
    ],
    cautionEn: 'Bend knees slightly if the lower back lifts.',
    cautionTh: 'งอเข่าเล็กน้อยถ้าหลังล่างยกจากพื้น',
  ),
  Exercise(
    id: 'russian_twist',
    nameEn: 'Russian Twist',
    nameTh: 'รัสเซียนทวิสต์',
    muscle: 'core',
    difficulty: 2,
    stepsEn: [
      'Sit with knees bent, lean back slightly, chest up.',
      'Rotate the torso side to side, touching the floor beside the hips.',
      'Lift feet off the floor to increase difficulty.',
    ],
    stepsTh: [
      'นั่งชันเข่า เอนตัวไปหลังเล็กน้อย อกตั้ง',
      'บิดลำตัวซ้าย-ขวา แตะพื้นข้างสะโพก',
      'ยกเท้าลอยจากพื้นเพื่อเพิ่มความยาก',
    ],
    cautionEn: 'Keep the spine long - do not round the back.',
    cautionTh: 'หลังตรง อย่างอหลัง',
  ),
  Exercise(
    id: 'dead_bug',
    nameEn: 'Dead Bug',
    nameTh: 'เดดบั๊ก',
    muscle: 'core',
    difficulty: 1,
    stepsEn: [
      'Lie on your back, arms up, knees bent 90 degrees over hips.',
      'Lower one arm and the opposite leg toward the floor slowly.',
      'Return and switch sides. Keep the lower back pressed down.',
    ],
    stepsTh: [
      'นอนหงาย ยกแขนขึ้น งอเข่า 90 องศาเหนือสะโพก',
      'เหยียดแขนหนึ่งและขาฝั่งตรงข้ามลงหาพื้นช้าๆ',
      'กลับท่าเดิมแล้วสลับข้าง กดหลังล่างแนบพื้นตลอด',
    ],
    cautionEn: 'Great safe core move for beginners.',
    cautionTh: 'ท่าปลอดภัย เหมาะกับมือใหม่',
  ),
  Exercise(
    id: 'bird_dog',
    nameEn: 'Bird Dog',
    nameTh: 'เบิร์ดด็อก',
    muscle: 'back',
    difficulty: 1,
    stepsEn: [
      'Start on hands and knees.',
      'Extend one arm forward and the opposite leg back until straight.',
      'Hold 2 seconds, return, switch sides.',
    ],
    stepsTh: [
      'เริ่มท่าคลาน มือและเข่าอยู่บนพื้น',
      'เหยียดแขนหนึ่งไปหน้าและขาฝั่งตรงข้ามไปหลังจนตรง',
      'ค้าง 2 วินาที กลับท่าเดิม สลับข้าง',
    ],
    cautionEn: 'Keep hips square to the floor.',
    cautionTh: 'สะโพกขนานพื้น อย่าบิดเอียง',
  ),
  Exercise(
    id: 'hollow_hold',
    nameEn: 'Hollow Body Hold',
    nameTh: 'ฮอลโลว์โฮลด์',
    muscle: 'core',
    difficulty: 3,
    stepsEn: [
      'Lie on your back, press the lower back into the floor.',
      'Lift shoulders and straight legs slightly off the floor, arms overhead.',
      'Hold the banana shape for the target time.',
    ],
    stepsTh: [
      'นอนหงาย กดหลังล่างแนบพื้น',
      'ยกไหล่และขาตรงลอยจากพื้นเล็กน้อย แขนเหยียดเหนือหัว',
      'ค้างท่ารูปกล้วยตามเวลาที่กำหนด',
    ],
    cautionEn: 'Bend knees or raise legs higher to make easier.',
    cautionTh: 'งอเข่าหรือยกขาสูงขึ้นถ้ายากเกินไป',
  ),
  Exercise(
    id: 'v_up',
    nameEn: 'V-up',
    nameTh: 'วีอัพ',
    muscle: 'core',
    difficulty: 3,
    stepsEn: [
      'Lie flat with arms overhead.',
      'Lift legs and torso together, reaching hands toward feet.',
      'Lower with control and repeat.',
    ],
    stepsTh: [
      'นอนราบ แขนเหยียดเหนือศีรษะ',
      'ยกขาและลำตัวขึ้นพร้อมกัน มือแตะปลายเท้า',
      'ลดลงอย่างควบคุมแล้วทำซ้ำ',
    ],
    cautionEn: 'Do tuck-ups (bent knees) if too hard.',
    cautionTh: 'ถ้ายากไปให้งอเข่าแทน',
  ),
  Exercise(
    id: 'flutter_kick',
    nameEn: 'Flutter Kicks',
    nameTh: 'เตะสลับขา',
    muscle: 'core',
    difficulty: 2,
    stepsEn: [
      'Lie back, hands under hips, legs straight and slightly lifted.',
      'Kick legs up and down in small, quick alternating motions.',
      'Keep the lower back pressed into the floor.',
    ],
    stepsTh: [
      'นอนหงาย มือรองใต้สะโพก ขาตรงยกลอยเล็กน้อย',
      'เตะขาสลับขึ้นลงเป็นจังหวะสั้นๆ เร็วๆ',
      'กดหลังล่างแนบพื้นตลอด',
    ],
    cautionEn: 'Stop if the lower back starts to arch.',
    cautionTh: 'หยุดถ้าหลังล่างเริ่มแอ่น',
  ),
  Exercise(
    id: 'mountain_climber',
    nameEn: 'Mountain Climber',
    nameTh: 'ปีนเขา (เมาน์เทนไคลม์เบอร์)',
    muscle: 'cardio',
    difficulty: 2,
    stepsEn: [
      'Start in a high plank.',
      'Drive one knee toward the chest, then quickly switch legs.',
      'Keep hips low and core tight, like running in plank.',
    ],
    stepsTh: [
      'เริ่มท่าแพลงก์แขนตรง',
      'ดึงเข่าหนึ่งเข้าหาอก แล้วสลับขาเร็วๆ',
      'สะโพกต่ำ เกร็งหน้าท้อง เหมือนวิ่งในท่าแพลงก์',
    ],
    cautionEn: 'Slow down if hips bounce up.',
    cautionTh: 'ช้าลงถ้าสะโพกเด้งขึ้น',
  ),

  // ================= BACK =================
  Exercise(
    id: 'superman',
    nameEn: 'Superman',
    nameTh: 'ซูเปอร์แมน',
    muscle: 'back',
    difficulty: 1,
    stepsEn: [
      'Lie face down, arms extended forward.',
      'Lift arms, chest, and legs off the floor together.',
      'Hold 2 seconds, lower slowly.',
    ],
    stepsTh: [
      'นอนคว่ำ แขนเหยียดไปหน้า',
      'ยกแขน อก และขาขึ้นจากพื้นพร้อมกัน',
      'ค้าง 2 วินาที แล้วลดลงช้าๆ',
    ],
    cautionEn: 'Lift gently - no jerking.',
    cautionTh: 'ยกเบาๆ อย่ากระชาก',
  ),
  Exercise(
    id: 'reverse_snow_angel',
    nameEn: 'Reverse Snow Angel',
    nameTh: 'สโนว์แองเจิลคว่ำ',
    muscle: 'back',
    difficulty: 2,
    stepsEn: [
      'Lie face down, arms at your sides, chest slightly lifted.',
      'Sweep arms overhead along the floor and back to the hips.',
      'Keep arms hovering off the floor the whole time.',
    ],
    stepsTh: [
      'นอนคว่ำ แขนแนบลำตัว ยกอกขึ้นเล็กน้อย',
      'กวาดแขนขึ้นเหนือหัวแล้วกลับมาที่สะโพก',
      'แขนลอยจากพื้นตลอดการเคลื่อนไหว',
    ],
    cautionEn: 'Move slowly for shoulder health.',
    cautionTh: 'ทำช้าๆ เพื่อถนอมหัวไหล่',
  ),
  Exercise(
    id: 'table_row',
    nameEn: 'Inverted Row (under table)',
    nameTh: 'โหนดึงตัวใต้โต๊ะ',
    muscle: 'back',
    difficulty: 3,
    equipEn: 'Very sturdy table',
    equipTh: 'โต๊ะที่แข็งแรงมาก',
    stepsEn: [
      'Lie under a sturdy table, grab the edge with both hands.',
      'Pull your chest up to the edge, body straight.',
      'Lower slowly. Bend knees to make it easier.',
    ],
    stepsTh: [
      'นอนใต้โต๊ะที่แข็งแรง จับขอบโต๊ะสองมือ',
      'ดึงอกขึ้นหาขอบโต๊ะ ลำตัวตรง',
      'ลดตัวลงช้าๆ งอเข่าเพื่อให้ง่ายขึ้น',
    ],
    cautionEn: 'Test that the table holds your weight first!',
    cautionTh: 'ทดสอบว่าโต๊ะรับน้ำหนักได้ก่อนเสมอ!',
  ),
  Exercise(
    id: 'ytw_raise',
    nameEn: 'Y-T-W Raise',
    nameTh: 'ยกแขนรูป Y-T-W',
    muscle: 'back',
    difficulty: 1,
    stepsEn: [
      'Lie face down, lift chest slightly.',
      'Raise arms in a Y shape, lower, then T shape, then W shape.',
      'That is one rep. Squeeze shoulder blades each time.',
    ],
    stepsTh: [
      'นอนคว่ำ ยกอกขึ้นเล็กน้อย',
      'ยกแขนเป็นรูป Y ลดลง แล้วรูป T แล้วรูป W',
      'นับเป็น 1 ครั้ง บีบสะบักทุกจังหวะ',
    ],
    cautionEn: 'Thumbs point up in every position.',
    cautionTh: 'หัวแม่มือชี้ขึ้นทุกท่า',
  ),
  Exercise(
    id: 'pull_up',
    nameEn: 'Pull-up',
    nameTh: 'ดึงข้อ',
    muscle: 'back',
    difficulty: 3,
    equipEn: 'Pull-up bar',
    equipTh: 'บาร์โหน',
    stepsEn: [
      'Hang from a bar, hands slightly wider than shoulders.',
      'Pull your chin above the bar, leading with the chest.',
      'Lower slowly to a full hang.',
    ],
    stepsTh: [
      'โหนบาร์ มือกว้างกว่าไหล่เล็กน้อย',
      'ดึงตัวขึ้นจนคางพ้นบาร์ อกนำ',
      'ลดตัวลงช้าๆ จนแขนเหยียดสุด',
    ],
    cautionEn: 'Use a chair to assist or do slow negatives if too hard.',
    cautionTh: 'ใช้เก้าอี้ช่วย หรือฝึกเฉพาะช่วงลงช้าๆ ถ้ายังดึงไม่ขึ้น',
  ),

  // ================= SHOULDERS =================
  Exercise(
    id: 'pike_pushup',
    nameEn: 'Pike Push-up',
    nameTh: 'วิดพื้นท่าไพค์',
    muscle: 'shoulders',
    difficulty: 2,
    stepsEn: [
      'From push-up position, walk feet in and raise hips high (inverted V).',
      'Bend elbows to lower the top of your head toward the floor.',
      'Press back up.',
    ],
    stepsTh: [
      'จากท่าวิดพื้น เดินเท้าเข้าและยกสะโพกสูงเป็นรูปตัว V คว่ำ',
      'งอศอกลดศีรษะลงหาพื้น',
      'ดันตัวกลับขึ้น',
    ],
    cautionEn: 'Head touches lightly - never load the neck.',
    cautionTh: 'ศีรษะแตะพื้นเบาๆ ห้ามลงน้ำหนักที่คอ',
  ),
  Exercise(
    id: 'wall_handstand_hold',
    nameEn: 'Wall Handstand Hold',
    nameTh: 'ยืนมือพิงกำแพง',
    muscle: 'shoulders',
    difficulty: 3,
    equipEn: 'Wall',
    equipTh: 'กำแพง',
    stepsEn: [
      'Face away from the wall, place hands on the floor.',
      'Walk feet up the wall until the body is nearly vertical.',
      'Hold, then walk back down carefully.',
    ],
    stepsTh: [
      'หันหลังให้กำแพง วางมือบนพื้น',
      'ไต่เท้าขึ้นกำแพงจนตัวเกือบตั้งตรง',
      'ค้างท่า แล้วไต่ลงอย่างระมัดระวัง',
    ],
    cautionEn: 'Advanced - keep a clear soft area around you.',
    cautionTh: 'ท่ายาก เคลียร์พื้นที่รอบตัวให้ปลอดภัย',
  ),
  Exercise(
    id: 'arm_circles',
    nameEn: 'Arm Circles',
    nameTh: 'หมุนแขนเป็นวงกลม',
    muscle: 'shoulders',
    difficulty: 1,
    stepsEn: [
      'Stand with arms extended out to the sides.',
      'Make small circles forward for the set time.',
      'Reverse direction for the same time.',
    ],
    stepsTh: [
      'ยืนกางแขนออกด้านข้าง',
      'หมุนแขนเป็นวงเล็กไปด้านหน้า ตามเวลาที่กำหนด',
      'สลับหมุนกลับหลังเท่ากัน',
    ],
    cautionEn: 'Great warm-up for any upper body day.',
    cautionTh: 'เหมาะเป็นท่าวอร์มอัพก่อนเล่นท่อนบน',
  ),
  Exercise(
    id: 'plank_to_downdog',
    nameEn: 'Plank to Down Dog',
    nameTh: 'แพลงก์สลับท่าภูเขา',
    muscle: 'shoulders',
    difficulty: 1,
    stepsEn: [
      'Start in a high plank.',
      'Push hips up and back into an inverted V, heels toward the floor.',
      'Return to plank. Repeat smoothly.',
    ],
    stepsTh: [
      'เริ่มท่าแพลงก์แขนตรง',
      'ดันสะโพกขึ้นไปหลังเป็นรูปตัว V คว่ำ ส้นเท้ากดลง',
      'กลับสู่แพลงก์ ทำต่อเนื่องนุ่มนวล',
    ],
    cautionEn: 'Keep arms straight throughout.',
    cautionTh: 'แขนเหยียดตรงตลอดการเคลื่อนไหว',
  ),
  Exercise(
    id: 'shoulder_tap',
    nameEn: 'Plank Shoulder Taps',
    nameTh: 'แพลงก์แตะไหล่',
    muscle: 'shoulders',
    difficulty: 2,
    stepsEn: [
      'Hold a high plank with feet slightly wide.',
      'Lift one hand to tap the opposite shoulder.',
      'Alternate hands without rocking the hips.',
    ],
    stepsTh: [
      'ค้างท่าแพลงก์แขนตรง เท้าแยกกว้างเล็กน้อย',
      'ยกมือหนึ่งแตะไหล่ฝั่งตรงข้าม',
      'สลับมือโดยสะโพกไม่ส่ายไปมา',
    ],
    cautionEn: 'Slower is better - fight the rotation.',
    cautionTh: 'ทำช้าๆ ดีกว่า พยายามไม่ให้ตัวบิด',
  ),

  // ================= ARMS =================
  Exercise(
    id: 'tricep_dips',
    nameEn: 'Chair Tricep Dips',
    nameTh: 'ดิพไทรเซปกับเก้าอี้',
    muscle: 'arms',
    difficulty: 2,
    equipEn: 'Sturdy chair',
    equipTh: 'เก้าอี้ที่มั่นคง',
    stepsEn: [
      'Sit on the chair edge, hands gripping beside hips, slide hips off.',
      'Bend elbows to lower the body, elbows pointing back.',
      'Press back up. Straighten legs to increase difficulty.',
    ],
    stepsTh: [
      'นั่งขอบเก้าอี้ มือจับข้างสะโพก เลื่อนก้นออกจากเก้าอี้',
      'งอศอกลดตัวลง ศอกชี้ไปด้านหลัง',
      'ดันขึ้น เหยียดขาตรงเพื่อเพิ่มความยาก',
    ],
    cautionEn: 'Keep shoulders down, away from ears.',
    cautionTh: 'กดไหล่ลง อย่ายกไหล่ชิดหู',
  ),
  Exercise(
    id: 'plank_up_down',
    nameEn: 'Plank Up-Downs',
    nameTh: 'แพลงก์ขึ้น-ลง',
    muscle: 'arms',
    difficulty: 2,
    stepsEn: [
      'Start in a forearm plank.',
      'Push up onto one hand, then the other, into a high plank.',
      'Lower back to forearms one arm at a time. Alternate the lead arm.',
    ],
    stepsTh: [
      'เริ่มท่าแพลงก์ศอก',
      'ดันขึ้นทีละมือจนเป็นแพลงก์แขนตรง',
      'ลดกลับลงทีละศอก สลับแขนนำ',
    ],
    cautionEn: 'Keep hips as still as possible.',
    cautionTh: 'พยายามให้สะโพกนิ่งที่สุด',
  ),
  Exercise(
    id: 'doorway_curl',
    nameEn: 'Towel Isometric Curl',
    nameTh: 'ม้วนแขนกับผ้าขนหนู',
    muscle: 'arms',
    difficulty: 1,
    equipEn: 'Towel',
    equipTh: 'ผ้าขนหนู',
    stepsEn: [
      'Step on the middle of a towel, hold both ends.',
      'Curl up hard against the towel resistance for 5 seconds.',
      'Release slowly. Adjust foot pressure to set difficulty.',
    ],
    stepsTh: [
      'เหยียบกลางผ้าขนหนู จับปลายทั้งสองข้าง',
      'ออกแรงม้วนแขนสู้แรงต้านผ้า ค้าง 5 วินาที',
      'ปล่อยช้าๆ ปรับแรงกดเท้าเพื่อเพิ่ม-ลดความหนัก',
    ],
    cautionEn: 'Keep breathing during the hold.',
    cautionTh: 'หายใจตามปกติระหว่างเกร็ง',
  ),

  // ================= CARDIO / FULL BODY =================
  Exercise(
    id: 'jumping_jack',
    nameEn: 'Jumping Jacks',
    nameTh: 'กระโดดตบ',
    muscle: 'cardio',
    difficulty: 1,
    stepsEn: [
      'Stand with feet together, arms at sides.',
      'Jump feet wide while raising arms overhead.',
      'Jump back to the start. Repeat rhythmically.',
    ],
    stepsTh: [
      'ยืนเท้าชิด แขนแนบลำตัว',
      'กระโดดแยกเท้าพร้อมยกแขนขึ้นเหนือหัว',
      'กระโดดกลับท่าเดิม ทำเป็นจังหวะต่อเนื่อง',
    ],
    cautionEn: 'Step out instead of jumping for low impact.',
    cautionTh: 'เปลี่ยนเป็นก้าวแตะแทนกระโดดได้ถ้าต้องการแรงกระแทกต่ำ',
  ),
  Exercise(
    id: 'burpee',
    nameEn: 'Burpee',
    nameTh: 'เบอร์พี',
    muscle: 'cardio',
    difficulty: 3,
    stepsEn: [
      'From standing, squat down and place hands on the floor.',
      'Jump feet back to plank, do a push-up (optional).',
      'Jump feet forward and leap up with arms overhead.',
    ],
    stepsTh: [
      'จากท่ายืน ย่อลงวางมือบนพื้น',
      'กระโดดเท้าไปหลังเป็นแพลงก์ วิดพื้น 1 ครั้ง (เลือกได้)',
      'กระโดดเท้ากลับแล้วดีดตัวขึ้น แขนชูเหนือหัว',
    ],
    cautionEn: 'Step back instead of jumping to reduce impact.',
    cautionTh: 'ก้าวถอยแทนกระโดดเพื่อลดแรงกระแทก',
  ),
  Exercise(
    id: 'high_knees',
    nameEn: 'High Knees',
    nameTh: 'วิ่งยกเข่าสูง',
    muscle: 'cardio',
    difficulty: 2,
    stepsEn: [
      'Run in place, driving knees up to hip height.',
      'Pump the arms as you run.',
      'Stay light on the balls of your feet.',
    ],
    stepsTh: [
      'วิ่งอยู่กับที่ ยกเข่าสูงถึงระดับสะโพก',
      'แกว่งแขนตามจังหวะวิ่ง',
      'ลงน้ำหนักเบาๆ ที่ปลายเท้า',
    ],
    cautionEn: 'March in place for a low-impact version.',
    cautionTh: 'เดินยกเข่าแทนได้ถ้าต้องการแรงกระแทกต่ำ',
  ),
  Exercise(
    id: 'butt_kicks',
    nameEn: 'Butt Kicks',
    nameTh: 'วิ่งส้นแตะก้น',
    muscle: 'cardio',
    difficulty: 1,
    stepsEn: [
      'Run in place, kicking heels toward the glutes.',
      'Keep knees pointing down.',
      'Move arms in a running motion.',
    ],
    stepsTh: [
      'วิ่งอยู่กับที่ เตะส้นเท้าไปแตะก้น',
      'เข่าชี้ลงพื้นตลอด',
      'แกว่งแขนเหมือนวิ่งปกติ',
    ],
    cautionEn: 'Good warm-up before leg workouts.',
    cautionTh: 'ใช้วอร์มอัพก่อนเล่นขาได้ดี',
  ),
  Exercise(
    id: 'skater_jump',
    nameEn: 'Skater Jumps',
    nameTh: 'กระโดดสเก็ต',
    muscle: 'cardio',
    difficulty: 2,
    stepsEn: [
      'Leap sideways onto one foot, swinging the other leg behind.',
      'Immediately leap to the other side.',
      'Swing arms for balance, like a speed skater.',
    ],
    stepsTh: [
      'กระโดดไปด้านข้างลงเท้าเดียว ขาอีกข้างเหวี่ยงไปด้านหลัง',
      'กระโดดสลับไปอีกฝั่งทันที',
      'แกว่งแขนช่วยทรงตัวเหมือนนักสเก็ต',
    ],
    cautionEn: 'Land softly with a bent knee.',
    cautionTh: 'ลงพื้นเบาๆ เข่างอเสมอ',
  ),
  Exercise(
    id: 'jump_rope',
    nameEn: 'Jump Rope',
    nameTh: 'กระโดดเชือก',
    muscle: 'cardio',
    difficulty: 2,
    equipEn: 'Jump rope',
    equipTh: 'เชือกกระโดด',
    stepsEn: [
      'Hold handles at hip height, elbows close to the body.',
      'Spin the rope with the wrists, jump just high enough to clear it.',
      'Keep a steady rhythm, land softly.',
    ],
    stepsTh: [
      'จับด้ามเชือกระดับสะโพก ศอกแนบลำตัว',
      'หมุนเชือกด้วยข้อมือ กระโดดพ้นเชือกแค่พอดี',
      'รักษาจังหวะสม่ำเสมอ ลงเท้าเบาๆ',
    ],
    cautionEn: 'No rope? Mimic the motion (phantom rope).',
    cautionTh: 'ไม่มีเชือกก็ทำท่าเลียนแบบได้',
  ),
  Exercise(
    id: 'bear_crawl',
    nameEn: 'Bear Crawl',
    nameTh: 'คลานหมี',
    muscle: 'cardio',
    difficulty: 2,
    stepsEn: [
      'Start on hands and feet, knees hovering just off the floor.',
      'Crawl forward moving opposite hand and foot together.',
      'Crawl backward to return. Keep hips low and level.',
    ],
    stepsTh: [
      'เริ่มด้วยมือและเท้ายันพื้น เข่าลอยเหนือพื้นเล็กน้อย',
      'คลานไปหน้า ขยับมือและเท้าฝั่งตรงข้ามพร้อมกัน',
      'คลานถอยหลังกลับ สะโพกต่ำและนิ่ง',
    ],
    cautionEn: 'Keep the back flat like a table.',
    cautionTh: 'หลังแบนราบเหมือนโต๊ะตลอด',
  ),
  Exercise(
    id: 'inchworm',
    nameEn: 'Inchworm',
    nameTh: 'หนอนคืบ',
    muscle: 'cardio',
    difficulty: 1,
    stepsEn: [
      'Stand, bend forward, and touch the floor.',
      'Walk hands out to a plank, hold 1 second.',
      'Walk hands back and stand up. Repeat.',
    ],
    stepsTh: [
      'ยืนก้มตัวแตะพื้น',
      'เดินมือออกไปจนเป็นท่าแพลงก์ ค้าง 1 วินาที',
      'เดินมือกลับแล้วยืนขึ้น ทำซ้ำ',
    ],
    cautionEn: 'Bend knees as needed for tight hamstrings.',
    cautionTh: 'งอเข่าได้ถ้าตึงหลังขา',
  ),
  Exercise(
    id: 'squat_hold_pulse',
    nameEn: 'Squat Pulse',
    nameTh: 'สควอทค้างเด้ง',
    muscle: 'legs',
    difficulty: 2,
    stepsEn: [
      'Lower into a squat and stay there.',
      'Pulse up and down a few centimeters.',
      'Keep tension in the thighs the whole set.',
    ],
    stepsTh: [
      'ย่อสควอทแล้วค้างไว้',
      'เด้งขึ้น-ลงเบาๆ ไม่กี่เซนติเมตร',
      'เกร็งต้นขาตลอดทั้งเซ็ต',
    ],
    cautionEn: 'Burning thighs are normal - sharp knee pain is not.',
    cautionTh: 'ขาแสบร้อนคือปกติ แต่ถ้าเจ็บแปลบที่เข่าให้หยุด',
  ),
  Exercise(
    id: 'standing_march',
    nameEn: 'Standing March',
    nameTh: 'เดินยกเข่าอยู่กับที่',
    muscle: 'cardio',
    difficulty: 1,
    stepsEn: [
      'March in place, lifting knees to hip height.',
      'Swing opposite arm with each step.',
      'Keep a brisk, steady pace.',
    ],
    stepsTh: [
      'เดินอยู่กับที่ ยกเข่าสูงระดับสะโพก',
      'แกว่งแขนสลับกับขา',
      'รักษาจังหวะเร็วสม่ำเสมอ',
    ],
    cautionEn: 'Perfect low-impact cardio for beginners.',
    cautionTh: 'คาร์ดิโอแรงกระแทกต่ำ เหมาะกับมือใหม่มาก',
  ),
  Exercise(
    id: 'sit_to_stand',
    nameEn: 'Sit-to-Stand',
    nameTh: 'ลุก-นั่งเก้าอี้',
    muscle: 'legs',
    difficulty: 1,
    equipEn: 'Chair',
    equipTh: 'เก้าอี้',
    stepsEn: [
      'Sit on a chair, arms crossed on your chest.',
      'Stand up fully without using your hands.',
      'Sit back down slowly with control.',
    ],
    stepsTh: [
      'นั่งบนเก้าอี้ กอดอกไว้',
      'ลุกขึ้นยืนโดยไม่ใช้มือช่วย',
      'นั่งลงช้าๆ อย่างควบคุม',
    ],
    cautionEn: 'Great starter move before squats.',
    cautionTh: 'ท่าเริ่มต้นที่ดีก่อนฝึกสควอท',
  ),
];
